steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "client/Dockerfile",
        "-t",
        "asia-south1-docker.pkg.dev/$PROJECT_ID/warranty-repo/frontend-service",
        "."
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-south1-docker.pkg.dev/$PROJECT_ID/warranty-repo/frontend-service"
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "frontend-service",
        "--image",
        "asia-south1-docker.pkg.dev/$PROJECT_ID/warranty-repo/frontend-service",
        "--region",
        "asia-south1",
        "--platform",
        "managed",
        "--allow-unauthenticated"
      ]