steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "server/Dockerfile",
        "-t",
        "asia-south1-docker.pkg.dev/$PROJECT_ID/warranty-repo/backend-service",
        "./server"
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-south1-docker.pkg.dev/$PROJECT_ID/warranty-repo/backend-service"
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "backend-service",

        "--image",
        "asia-south1-docker.pkg.dev/$PROJECT_ID/warranty-repo/backend-service",

        "--region",
        "asia-south1",

        "--platform",
        "managed",

        "--allow-unauthenticated",

        "--add-cloudsql-instances",
        "$PROJECT_ID:asia-south1:warrantytracker",

        "--set-env-vars",
        "DB_USERNAME=postgres,DB_PASSWORD=Postgres@18,DB_NAME=warrantytracker,JWT_SECRET=12345Secret54321,INSTANCE_CONNECTION_NAME=$PROJECT_ID:asia-south1:warrantytracker"
      ]

options:
  logging: CLOUD_LOGGING_ONLY